version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: examen_nest_shino
    restart: always
    environment:
      POSTGRES_DB: examen_nest_2
      POSTGRES_USER: santiago
      POSTGRES_PASSWORD: santiago
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: